name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run tests
        run: npm test
        
      - name: Build
        run: npm run build
        
      - name: Package
        run: npm run package
        
      - name: Extract version
        id: version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
      - name: Check for release notes
        id: release_notes
        run: |
          if [ -f "GITHUB_RELEASE_${{ steps.version.outputs.version }}.md" ]; then
            echo "notes_file=GITHUB_RELEASE_${{ steps.version.outputs.version }}.md" >> $GITHUB_OUTPUT
            echo "has_notes=true" >> $GITHUB_OUTPUT
          else
            echo "has_notes=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: "future-commit ${{ steps.version.outputs.version }}"
          body_path: ${{ steps.release_notes.outputs.has_notes == 'true' && steps.release_notes.outputs.notes_file || '' }}
          draft: false
          prerelease: false
          files: |
            dist/future-commit
            build/index.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}